import DefaultNode from '../components/NodeConfigModal';
export const nodeTypes = {
  summarizetext: DefaultNode,
  classifytext: DefaultNode,
  extractentities: DefaultNode,
  sentimentanalysis: DefaultNode,
  generatetext: DefaultNode,
  texttospeech: DefaultNode,
  imageanalysis: DefaultNode,
  documentocr: DefaultNode,

  condition: DefaultNode,
  loopforeach: DefaultNode,
  delay: DefaultNode,
  terminate: DefaultNode,

  buildjson: DefaultNode,
  mergejson: DefaultNode,
  parsecsv: DefaultNode,
  jsontocsv: DefaultNode,
  flattenjson: DefaultNode,
  renamejsonkeys: DefaultNode,
  mathexpression: DefaultNode,
  filterdata: DefaultNode,
  texttemplate: DefaultNode,
  stringformatter: DefaultNode,
  extractfield: DefaultNode,
  customdatatransformation: DefaultNode,

  readfile: DefaultNode,
  writefile: DefaultNode,
  appendtofile: DefaultNode,
  generatepdf: DefaultNode,
  uploadtos3: DefaultNode,
  downloadfroms3: DefaultNode,
  lists3files: DefaultNode,
  putitem: DefaultNode,
  getitem: DefaultNode,
  scandynamodb: DefaultNode,

  httprequest: DefaultNode,
  graphqlrequest: DefaultNode,
  crmsync: DefaultNode,
  twiliosms: DefaultNode,
  sendtoslack: DefaultNode,

  manualtrigger: DefaultNode,
  apigatewaytrigger: DefaultNode,
  s3trigger: DefaultNode,
  eventbridgetrigger: DefaultNode,
  scheduletrigger: DefaultNode,
  dynamodbtrigger: DefaultNode,
  snstrigger: DefaultNode,

  sendemail: DefaultNode,
  sendsms: DefaultNode,
  pushnotification: DefaultNode,

  formtrigger: DefaultNode,
  humanapproval: DefaultNode,
  dashboardupdate: DefaultNode,

  generateuuid: DefaultNode,

  logtoconsole: DefaultNode,
  mockdata: DefaultNode,
  viewcontext: DefaultNode,
  comment: DefaultNode,
  breakpoint: DefaultNode,
};
